[compiler.solc]
exclude_paths = ["venv", ".venv", "test", "node_modules", "lib", "script"]
include_paths = ["node_modules"]

[compiler.solc.optimizer]
runs = 200

[detectors]
exclude = []
ignore_paths = ["venv", ".venv", "test"]
exclude_paths = ["venv", ".venv", "test", "node_modules", "lib", "script"]

[testing]
cmd = "anvil"

[testing.anvil]
cmd_args = "--prune-history 100 --transaction-block-keeper 10 --steps-tracing --silent"

[testing.hardhat]
cmd_args = ""